---
title: Capture Life
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: dino@oat-bot.com
description: 'Capture Life is a project created by photographer Grazina Zizaite to
  support and raise awareness about the work of the natural birth and healthcare centre,
  Bumi Sehat in Bali.

'
baseurl: ''
url: ''
markdown: kramdown
gems:
- jekyll-feed
- jekyll-autoprefixer
sass:
  sass_dir: _sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
